/* Generated by Together */

#ifndef CCIRCLE_H
#define CCIRCLE_H

#include <string>

#include "CGraphicElement.h"

namespace GraSys {
class CCircle : public CGraphicElement {
private:
    double m_radius;

public:
    /**
     * Constructor
     *
     * @param color 	the color
     */
    CCircle(std::string color = "black", const CCoordinate& center = GraSys::CCoordinate(0,0), double radius = 0);
    // required for polymorphism
    ~CCircle();
    double getRadius();
    void setRadius(double radius);
    void setCenter(const CCoordinate& center);
    void print();
    bool operator== (const CCircle& c) const;
};
}

#endif //CCIRCLE_H
