/* Generated by Together */

#ifndef CRECTANGLE_H
#define CRECTANGLE_H

#include <string>

#include "CGraphicElement.h"

namespace GraSys {
template<typename T>
class CRectangle : public CGraphicElement<T> {

public:
	CRectangle(string color = "black") : GraSys::CGraphicElement<T>("CRectangle", 2, color) {
	}

	CRectangle(string color, const CCoordinate<T>& corner1, const CCoordinate<T>& corner2) :
		GraSys::CGraphicElement<T>("CRectangle", 2, color) {
		GraSys::CGraphicElement<T>::m_color = color;
		GraSys::CGraphicElement<T>::m_coordinates.push_back(corner1);
		GraSys::CGraphicElement<T>::m_coordinates.push_back(corner2);
	}

	~CRectangle() {

	}
};
}
#endif //CRECTANGLE_H
