/* Generated by Together */

#ifndef CRECTANGLE_H
#define CRECTANGLE_H

#include <string>

#include "CGraphicElement.h"

namespace GraSys {
class CRectangle : public CGraphicElement {

protected:
    string getTypeName();

public:
	CRectangle(string color = "black");
	CRectangle(string color, const CCoordinate& corner1, const CCoordinate& corner2);
	~CRectangle();
};
}
#endif //CRECTANGLE_H
