/* Generated by Together */

#ifndef CTRIANGLE_H
#define CTRIANGLE_H

#include <string>
using namespace std;

#include "CGraphicElement.h"

namespace GraSys {
class CTriangle : public CGraphicElement {

public:
	CTriangle (string color);
	CTriangle (string color, const CCoordinate& corner1, const CCoordinate& corner2, const CCoordinate& corner3);
	~CTriangle();
protected:
    string getTypeName();

};
}
#endif //CTRIANGLE_H
